# List comprehension

Understanding list comprehensions lets you define long lists in a manner that
is both both elegant and saves you a lot of time. The first time you see a list
comprehension it may seem daunting, but they’re relatively simple once you
understand how they work.

Here’s a challenge for you: Using a single line of code, get a list of the squares of each number between 0 and 100! 

In [1]:
nums_squared = [num**2 for num in range(0,101)]

Then do it again, but only include those
squares which are even numbers.

In [2]:
even_squares = [num_squared for num_squared in nums_squared if num_squared%2==0]

# Generators

Generators are an important tool for training deep neural networks. because
they let you iterate over data without cluttering your computer’s memory all
that much. 

Implement a generator function which returns a meow the first time
you call it, and then twice the number of meows on each consecutive call.

In [3]:
def infinite_meows():
    num_of_meows = 1
    while True:
        yield 'Meow '* num_of_meows
        num_of_meows *= 2
        
def definite_meows(steps):
    num_of_meows, step_cnt = 1, 0
    while step_cnt < steps: 
        yield 'Meow '* num_of_meows
        num_of_meows *= 2
        step_cnt += 1

In [4]:
meowerator = infinite_meows()
for i in range(0,4):
    print(next(meowerator))

Meow 
Meow Meow 
Meow Meow Meow Meow 
Meow Meow Meow Meow Meow Meow Meow Meow 


In [5]:
purrator = definite_meows(4)
for purr in purrator:
    print(purr)

Meow 
Meow Meow 
Meow Meow Meow Meow 
Meow Meow Meow Meow Meow Meow Meow Meow 


# NumPy

NumPy is an important library for working with multidimensional arrays, matri-
ces and doing math in general. If you don’t have NumPy, use conda to install it
now; though if you followed our setup guide, NumPy should have been installed
into your virtual environment along with it TensorFlow. See if you can:

1. Create a $5\times5$ NumPy array filled with normally distributed (i.e. $\mu = 0,\sigma = 1$)

In [6]:
import numpy as np

In [7]:
mu, sigma, shape = 0,1,(5,5)
norm_arr = np.random.normal(mu, sigma, shape)
print(norm_arr)

[[ 0.18091865 -0.40209879 -2.36505738  0.30965682  0.75883653]
 [ 0.25544035  1.20033303 -1.18238236  1.3241387  -0.59347757]
 [-0.07991821 -0.85971944  0.91403091 -1.18320835  0.63361677]
 [ 0.3779571   0.57658194  0.37953265 -0.58622556  0.72576244]
 [ 0.71324125 -0.00407147 -0.314887    0.78522693 -1.19270914]]


2. If the value of an entry is greater than $0.09$, replace it with its square. Else, replace it with $42$.

In [11]:
norm_arr = np.where(norm_arr > 0.09, norm_arr**2, 42.0)
print(norm_arr.astype('int'))

[[   1764 3111696 3111696      42       0]
 [   1764       4 3111696       9 3111696]
 [3111696 3111696       0 3111696       0]
 [     42       0      42 3111696       0]
 [      0 3111696 3111696       0 3111696]]


3. Use slicing to print just the fourth column of your array.

In [9]:
print(norm_arr[:,3])

[ 0.09588735  1.7533433  42.         42.          0.61658133]
