# List comprehension

Understanding list comprehensions lets you define long lists in a manner that
is both both elegant and saves you a lot of time. The first time you see a list
comprehension it may seem daunting, but they’re relatively simple once you
understand how they work.

Here’s a challenge for you: Using a single line of code, get a list of the squares of each number between 0 and 100! 

In [1]:
nums_squared = [num**2 for num in range(0,101)]

Then do it again, but only include those
squares which are even numbers.

In [2]:
even_squares = [num_squared for num_squared in nums_squared if num_squared%2==0]

# Generators

Generators are an important tool for training deep neural networks. because
they let you iterate over data without cluttering your computer’s memory all
that much. 

Implement a generator function which returns a meow the first time
you call it, and then twice the number of meows on each consecutive call.

In [3]:
def infinite_meows():
    num_of_meows = 1
    while True:
        yield 'Meow '* num_of_meows
        num_of_meows *= 2
        
def definite_meows(steps):
    num_of_meows, step_cnt = 1, 0
    while step_cnt < steps: 
        yield 'Meow '* num_of_meows
        num_of_meows *= 2
        step_cnt += 1

In [4]:
meowerator = infinite_meows()
for i in range(0,4):
    print(next(meowerator))

Meow 
Meow Meow 
Meow Meow Meow Meow 
Meow Meow Meow Meow Meow Meow Meow Meow 


In [5]:
purrator = definite_meows(4)
for purr in purrator:
    print(purr)

Meow 
Meow Meow 
Meow Meow Meow Meow 
Meow Meow Meow Meow Meow Meow Meow Meow 


# NumPy

NumPy is an important library for working with multidimensional arrays, matri-
ces and doing math in general. If you don’t have NumPy, use conda to install it
now; though if you followed our setup guide, NumPy should have been installed
into your virtual environment along with it TensorFlow. See if you can:

1. Create a $5\times5$ NumPy array filled with normally distributed values (i.e. $\mu = 0,\sigma = 1$)

In [6]:
import numpy as np

In [7]:
mu, sigma, shape = 0,1,(5,5)
norm_arr = np.random.normal(mu, sigma, shape)
print(norm_arr)

[[-0.16637519  0.39438085 -0.03124798 -0.25515333 -1.04627336]
 [ 1.20230955 -0.48253939  2.06279043  0.13411895 -0.16891235]
 [-1.41980568 -0.46816122  0.65750857 -0.42412813 -0.53039695]
 [ 1.0104455  -2.11688961  0.25790714 -0.14159368 -0.76017949]
 [ 0.8185031  -0.19728216  2.51042469  0.15429421 -0.64156073]]


2. If the value of an entry is greater than $0.09$, replace it with its square. Else, replace it with $42$.

In [8]:
norm_arr = np.where(norm_arr > 0.09, norm_arr**2, 42)
print(norm_arr)

[[4.20000000e+01 1.55536255e-01 4.20000000e+01 4.20000000e+01
  4.20000000e+01]
 [1.44554826e+00 4.20000000e+01 4.25510438e+00 1.79878938e-02
  4.20000000e+01]
 [4.20000000e+01 4.20000000e+01 4.32317524e-01 4.20000000e+01
  4.20000000e+01]
 [1.02100010e+00 4.20000000e+01 6.65160951e-02 4.20000000e+01
  4.20000000e+01]
 [6.69947320e-01 4.20000000e+01 6.30223212e+00 2.38067024e-02
  4.20000000e+01]]


3. Use slicing to print just the fourth column of your array.

In [9]:
print(norm_arr[:,3])

[4.20000000e+01 1.79878938e-02 4.20000000e+01 4.20000000e+01
 2.38067024e-02]
